spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/user
    username: postgres
    password: 123456

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        id:
          optimizer:
            pooled:
              preferred: none

  data:
    redis:
      port: 6379
      host: localhost

  mail:
    host: smtp.gmail.com
    port: 587
    username: nkocnox2004@gmail.com
    password: sldm bahx sbts oiap
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  signKey: "eb6dfa14f1cb61e65680efa7f671ec7c2da94ca1f43c80b57f91f9554ff6baae"
server:
  port: 8080
  address: 0.0.0.0
payos:
  client-id: "3149d006-a3f1-4367-918c-9b1d19f2ae11"
  api-key: "61566a25-fe4d-4ceb-bb26-3b9c704404f9"
  checksum-key: "ed744b8da5447ce2333708f30828e2e9207fa3e1804bc4e8fe415a6128943f9f"
